name: meu_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  brasil_fields: ^1.18.0
  firebase_auth: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
